# Generated by Django 4.0 on 2022-01-27 23:04

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasdeproducto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalindicadoresdeoferta',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical indicadores de oferta'},
        ),
        migrations.AlterModelOptions(
            name='historicalproducto',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical producto'},
        ),
        migrations.AlterModelOptions(
            name='historicalunidadesdemedida',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical unidades de medida'},
        ),
        migrations.AlterModelOptions(
            name='indicadoresdeoferta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unidadesdemedida',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoriasdeproducto',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='categoy_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoriasdeproducto', verbose_name='Categoria de Producto'),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='measure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.unidadesdemedida', verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoy_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoriasdeproducto', verbose_name='Categoria de Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.unidadesdemedida', verbose_name='Unidad de Medida'),
        ),
        migrations.CreateModel(
            name='HistoricalCategoriasDeProducto',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
            ],
            options={
                'verbose_name': 'historical categorias de producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
