# Generated by Django 4.0 on 2022-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_categoy_product_historicalindicadoresdeoferta_category_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del Producto'),
        ),
    ]
